@startuml RoleBasedSdlc

skinparam monochrome true
skinparam Shadowing false

start

:**Backlog Grooming - Product Owner**
1. Prioritize backlog items;

' T shirt size estimate

:**Sprint Planning - Scrum Master**
2. Lead ceremony;

:**Sprint Planning - Product Owner**
3. Present top backlog items;

:**Sprint Planning - Developers, QAs**
4. Estimate top backlog items with the scale 1, 2, 4, 8, etc.
The units could be hours or story points;

:**Sprint Planning - Developers, QAs**
5. Decide on how many top backlog
items can be worked on in the sprint;

:**Sprint Planning - Developers, QAs**
6. Create sprint backlog;

:**Daily Scrum - Scrum Master**
7. Lead ceremony;

:**Daily Scrum - Developers, QA**
8. Each person answers the following questions:
i. What did I accomplish yesterday?
ii. What will I accomplish today?
iii. Are there any impediments in my way?;

split

:**Development - Developers**
9a. Begin work on backlog items - development;

:**Development Complete - Developers**
;

split again

:**QA - QAs**
9b. Begin work on backlog items - test cases;

end split

end

@enduml